In [6]:
import pandas as pd
df_1=pd.read_csv("new_mungitura.csv")

C:\Users\digig\AppData\Local\Temp\ipykernel_5184\4198939064.py:2: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df_1=pd.read_csv("new_mungitura.csv")

In [4]:
df_1.to_csv("new_mungitura2.csv",sep=";",decimal=",")

In [7]:
df_2=pd.read_csv("new_traffico_animali.csv")
df_2.to_csv("new_traffico1.csv",sep=";",decimal=",")

C:\Users\digig\AppData\Local\Temp\ipykernel_5184\2475647443.py:1: DtypeWarning: Columns (0,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2=pd.read_csv("new_traffico_animali.csv")

In [8]:
df_2

,Numero animale,Nome gruppo,Data/Ora,Area precedente,Tempo nell'area (hh:mm),Nome dispositivo,Risultato,Decisione cancello,Intervallo Mungitura,Capezzoli non completamente munti,...,Tempo,Mese,Anno,Mese Anno,PD,AD,PS,AS,OreTotali,MinutiTotali
0,980,Asciutte,21/03/2022 08:46,MS1,06:26,MS1,NaN,NaN,NaN,NaN,...,08:46:00,3.0,2022.0,2022-03,0,0,0,0,6,26.0
1,0,0,0,0,0,0,0.00,0,0,0,...,0,0.0,0.0,0,0,0,0,0,0,0.0
2,980,Asciutte,20/03/2022 02:07,MS1,14:12,MS1,0.05,NaN,1 d 14:12,NaN,...,02:07:00,3.0,2022.0,2022-03,0,0,0,0,14,12.0
3,0,0,0,0,0,0,0.00,0,0,0,...,0,0.0,0.0,0,0,0,0,0,0,0.0
4,980,Asciutte,18/03/2022 11:52,MS1,06:12,MS1,0.01,NaN,06:12,NaN,...,11:52:00,3.0,2022.0,2022-03,0,0,0,0,6,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872745,0,0,0,0,0,0,0.00,0.0,0,0,...,0,0.0,0.0,0,0,0,0,0,0,0.0
872746,0,0,0,0,0,0,0.00,0.0,0,0,...,0,0.0,0.0,0,0,0,0,0,0,0.0
872747,0,0,0,0,0,0,0.00,0.0,0,0,...,0,0.0,0.0,0,0,0,0,0,0,0.0
872748,0,0,0,0,0,0,0.00,0.0,0,0,...,0,0.0,0.0,0,0,0,0,0,0,0.0
872749,PRECEDENTEMENTE IL GRUPPO E' COMPOSTO DA MANZE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaT,0,0,0,0,0,NaN